title: About

icon: 👤

columns:
  main:
    width: 1/1
    fields:
      content:
        label: Contenu
        type: blocks
        fieldsets:
          - article_heading
          - bullet_points
          - clients_list
          - collaborators_list
          - gallery
          - image
          - pages_list
          - prestations
          - profiles
          - sketch_text
          - space
          - text
          - use_case
          - video
