title: Projet

icon: 🖼️

status:
  draft:
    label: Brouillon
    text: Le projet est toujours en mode brouillon. Elle ne peut être vue que par les éditeurs ayant accès à l'administration.
  listed:
    label: Publié
    text: Le projet est en ligne.


columns:
  header_container:
    width: 1/1
    fields:
      baseline:
        width: 2/3
        label: Baseline
        type: text
      preview_full_size:
        label: Preview full size
        width: 1/3
        type: toggle
        text:
          - non (regular size)
          - oui (full size preview)
        default: false
      covers:
        width: 1/2
        required: false
        type: files
        multiple: true
        query: page.images.template('image')
        label: Image de couverture
        help: Image qui s'afficherons en apercu dans la liste de projet
        uploads:
          template: image
      miniature:
        width: 1/2
        required: true
        type: files
        multiple: false
        query: page.images.template('image')
        label: Image de miniature
        help: Image qui s'afficherons au hover
        uploads:
          template: image

      covers_video:
        width: 1/2
        required: false
        type: files
        multiple: true
        query: page.images.template('image')
        label: Video de couverture
        help: Video qui s'afficherons en apercu dans la liste de projet (si il ya une video, l'image de couverture ne s'affiche pas)
        uploads:
          template: video

  main:
    width: 3/4
    fields:
      intro:
        label: Introduction
        type: writer
        marks:
          - italic
          - link
        nodes:
          - heading
          - bulletList
          - orderedList
        headings:
          - 3
      content:
        label: Contenu
        type: blocks
        fieldsets:
          - article_heading
          - bullet_points
          - clients_list
          - collaborators_list
          - gallery
          - image
          - pages_list
          - profiles
          - sketch_text
          - space
          - text
          - video


  aside:
    width: 1/4
    fields:

      sectors:
        label: Secteur (type de projet)
        type: pages
        query: site.find('sectors').children
        multiple: true
        layout: list
        required: true

      clients:
        label: Client·e·xs
        type: pages
        query: site.find('clients').children
        multiple: true
        layout: list

      date:
        label: Période
        type: date
        required: true

      services:
        label: Service·s
        type: pages
        query: site.find('services').children
        multiple: true
        layout: list

      localisation:
        label: Lieu
        type: writer
        inline: true
        marks:
          - italic
          - link

      photo_credits:
        label: Photos
        type: writer
        inline: true
        marks:
          - italic
          - link

  gallery_column:
    width: 1/1
    fields:
      gallery:
        required: true
        type: files
        multiple: true
        query: page.images.template('image')
        label: Galerie preview
        help: Images qui s'afficherons pour l'aperçu du projet
        uploads:
          template: image
