name: Profiles
wysiwyg: true
preview: fields
fields:
  title:
    label: Titre
    type: text
  profiles_list:
    type: structure
    fields:
      photo:
        label: Photo
        type: files
        uploads:
          accept: image/*
        max: 1
        min: 0
        required: false
        layout: cards
        image:
          back: black
        size: huge
        width: 1/2
      first_name:
        label: prénom
        type: text
      last_name:
        label: nom
        type: text
      function:
        label: fonction
        type: text
      roles:
        label: Rôles
        type: list
